apiVersion: v1
kind: Pod
metadata:
  name: loop
spec:
  containers:
  - name: busybox
    image: busybox:1.36.1
    command: ["sh", "-c", "for i in {1..5}; do echo \"$i - A piece of cake !\"; done; sleep infinity"]

